# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Run hictk_integration_suite unit tests

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"

  pull_request:
    paths:
      - ".github/workflows/ci.yml"


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.12"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install h5py v3.12
        run: pip install 'h5py==3.12'

      - name: Inspect DLL
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call "%VCVARSALL%" x86
          dumpbin /dependents C:\hostedtoolcache\windows\Python\3.12.*\x64\Lib\site-packages\h5py\_errors*.pyd
      
      - name: Trigger import error
        run: python3 -v -c 'import h5py'

